# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.


version: '3.8'
services:

  database:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db
    networks:
      - app-network

  backend:
    container_name: backend-api
    image: backend-api
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MongoDbSettings__DatabaseName=admin
      - MongoDbSettings__CollectionName=User
      - MongoDbSettings__ConnectionString=mongodb://database:27017/
      - Jwt__Key=DhftOS5uphK3vmCJQrexST1RsyjZBjXWRgJMFPU4
      - Jwt__Issuer=https://localhost:5000/
      - Jwt__Audience=https://localhost:5000/
    ports:
      - 5000:5000
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    container_name: frontend-angular
    image: frontend-angular:1.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name : app-network

volumes:
  mongo-volume:
    name : mongo-volume
    external : false
  backend-volume:
    name : backend-volume
    external : false

