version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./mongo/data:/data/db
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 27017:27017

volumes:
  database-volume:
    name : database-volume
    external : false